### ISSUE TITLE
not all selected playables are added to the selectedPlayables set

### ISSUE THREAD

**Issue by afelley** [WhitmanSWDesignSpring2018/project-5-8-teamalpha#22]
When dragging to select playables, notes not inside the selection rectangle are not added to selectedPlayables even though they become selected as part of the gesture.setSelected method. This was causing issues in makeGroup that have been patched. It also probably affects ungroup.

**Comment by afelley** [comment]
Does not impact functionality

**Comment by afelley** [comment]
Should be fixed for the next release to prevent future issues

**Comment by ProfJanetDavis** [comment]
Get rid of selectedPlayables set - it's not being used in every case

**Comment by afelley** [comment]
selectedPlayables has been removed
