### ISSUE TITLE
Group Menu Button Part 1

### ISSUE THREAD

**Issue by ColinAslett** [WhitmanSWDesignSpring2018/project-5-8-teamalpha#3]
When the Group menu item is chosen, all selected note bars are grouped into one gesture. A gesture behaves as if it is just one note bar with a complex sound to it. Once note bars have been grouped into a gesture, selecting/deleting/dragging any one of the note bars in the gesture causes the same thing to happen to all the others in the gesture.

**Comment by kmargtaylor** [comment]
We did this!
