### ISSUE TITLE
Should the isGesture() method exist?

### ISSUE THREAD

**Issue by ProfJanetDavis** [WhitmanSWDesignSpring2018/project-5-8-teamalpha#47]
On the one hand, it is inelegant because it duplicates information with the object's class. 

On the other hand, it's elegant because this is a common operation (maybe?) and it improves readability.

https://github.com/WhitmanSWDesignSpring2018/project-5-8-teamalpha/blob/a746ee5db036244a419be920afd91bfb317f726c/src/tunecomposer/Playable.java#L44

**Comment by ColinAslett** [comment]
no
