### ISSUE TITLE
Why is this a Deque???

### ISSUE THREAD

**Issue by ColinAslett** [WhitmanSWDesignSpring2018/project-5-8-teamalpha#50]
https://github.com/WhitmanSWDesignSpring2018/project-5-8-teamalpha/blob/711287d0244e2d0de98b4943ce9879190d80bb2b/src/tunecomposer/CommandManager.java#L6

**Comment by ColinAslett** [comment]
CHANGE IT TO A STACK!!!!

**Comment by afelley** [comment]
you change it to a stack
