### ISSUE TITLE
ExceptionInInititalizerError, maybe don't make everything static?

### ISSUE THREAD

**Issue by ColinAslett** [WhitmanSWDesignSpring2018/project-5-8-teamalpha#62]
https://stackoverflow.com/questions/3375810/exception-in-initializer-error

**Comment by afelley** [comment]
you don't say

**Comment by ColinAslett** [comment]
https://stackoverflow.com/questions/44807580/javafx-access-parent-controller-class-from-fxml-child?rq=1

**Comment by afelley** [comment]
seems useful

**Comment by afelley** [comment]
this has been resolved by deciding not to refactor TuneComposer for this version
