### ISSUE TITLE
Edits to notes, including moving position and changing length, are never undoable

### ISSUE THREAD

**Issue by afelley** [WhitmanSWDesignSpring2018/project-5-8-teamalpha#67]
EditCommand was never fully implemented or tested so it doesn't work

**Comment by ProfJanetDavis** [comment]
You should probably have two separate commands, MoveCommand and (DurationCommand or StretchCommand).

In TuneComposer.handleNoteStopDragging(), before we call stopMoving() on the selected notes, get xoffset and yoffset from a selected playable and store them in the new MoveCommand. To undo, subtract these offsets from all selected playable's positions; to do or redo, add the offsets.
