### ISSUE TITLE
Gestures are not selected correctly after being pasted or loaded

### ISSUE THREAD

**Issue by afelley** [WhitmanSWDesignSpring2018/project-5-8-teamalpha#88]
gestures that have been parsed from xml do not seem to call setSelected correctly. They should select all of their contents as well as themselves but they only select the main rectangle. This doesn't occur on creation, only when selecting a gesture after it has been unselected.

**Comment by ColinAslett** [comment]
This seems like an impossible task, thus I am unassigning myself from this issue.

**Comment by ColinAslett** [comment]
This IS AN FXML ISSUE NOT A REAL CODING ISSUE
